language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    - alakhefifi@gmail.com
